name: growstreams
id: growstreams-1.0.0
version: 1.0.0
exposed: True
exposed-modules: GrowToken Test.UpdateRateTest HelloStream VestingStream StreamPool Test.GrowTokenTest MilestoneStream FeaturedAppActivity StreamCore Test.StreamCoreTest
import-dirs: ${pkgroot}/growstreams-1.0.0-a5f0e7360a19da9805facd40396ea0318adebfef4f1accdd8b5b01abd1c82749
library-dirs: ${pkgroot}/growstreams-1.0.0-a5f0e7360a19da9805facd40396ea0318adebfef4f1accdd8b5b01abd1c82749
data-dir: ${pkgroot}/growstreams-1.0.0-a5f0e7360a19da9805facd40396ea0318adebfef4f1accdd8b5b01abd1c82749
depends: daml-prim daml-stdlib-3.4.11
