name: growstreams
id: growstreams-1.0.0
version: 1.0.0
exposed: True
exposed-modules: GrowToken Test.UpdateRateTest HelloStream VestingStream StreamPool Test.GrowTokenTest MilestoneStream FeaturedAppActivity StreamCore Test.StreamCoreTest
import-dirs: ${pkgroot}/growstreams-1.0.0-ede21c7dd468efab3df48ff5638d165bd6a82f551f608ae19dbfecd21c3c6d84
library-dirs: ${pkgroot}/growstreams-1.0.0-ede21c7dd468efab3df48ff5638d165bd6a82f551f608ae19dbfecd21c3c6d84
data-dir: ${pkgroot}/growstreams-1.0.0-ede21c7dd468efab3df48ff5638d165bd6a82f551f608ae19dbfecd21c3c6d84
depends: daml-prim daml-stdlib-3.4.11
