name: growstreams
id: growstreams-1.0.0
version: 1.0.0
exposed: True
exposed-modules: GrowToken Test.UpdateRateTest HelloStream VestingStream StreamPool Test.GrowTokenTest MilestoneStream FeaturedAppActivity StreamCore Test.StreamCoreTest
import-dirs: ${pkgroot}/growstreams-1.0.0-bf1612db6f37cd558c184ea30682dd145f9951b81201ef1ba5d042f6edb3b175
library-dirs: ${pkgroot}/growstreams-1.0.0-bf1612db6f37cd558c184ea30682dd145f9951b81201ef1ba5d042f6edb3b175
data-dir: ${pkgroot}/growstreams-1.0.0-bf1612db6f37cd558c184ea30682dd145f9951b81201ef1ba5d042f6edb3b175
depends: daml-prim daml-stdlib-3.4.11
